### ISSUE TITLE
boolean invalid as a policy target

### ISSUE THREAD

**Issue by MiguelR8** [andreamargheri/FACPL#4]
I made the following FACPL policy:
```
PolicySet Fallback  { deny-unless-permit
	target: true
	policies:
	
	Rule rule2 ( deny ) 
	
	obl-p: [M log("Uncaught request detected!")]
}
```

But when I try to generate XACML I get the error:
```
Policy Fallback does not respect the restriction for the generation of XACML code!  Check FACPL's Guide

Check FACPL's Guide
```

And in the [guide](https://facpl.readthedocs.io/en/latest/txt/facpl.html?highlight=target), it says the target is a boolean expression. Isn't there a way to define a policy that is always applicable?

**Comment by andreamargheri** [comment]
Hi @MiguelR8 

to translate to XACML policy you require to follow the [XACML code structure](http://docs.oasis-open.org/xacml/3.0/xacml-3.0-core-spec-os-en.html#_Toc325047111)  

For some examples check the XTEXT [tests](https://github.com/andreamargheri/FACPL/blob/master/XTEXT/it.unifi.xtext.facpl2.tests/src/it/unifi/xtext/facpl2/tests/xacml/XACMLtranslation_Test.xtend) 

As you can see for the tests, compliance with XACML syntax (and hence the possibility to translate to it) is checked by a [validator](https://github.com/andreamargheri/FACPL/blob/master/XTEXT/it.unifi.xtext.facpl2/src/it/unifi/xtext/facpl/validation/Facpl2Xacml_Validator.xtend). Hence, a ```true``` target is not compliant (if not part of another function) as per the control at row 69

**Comment by MiguelR8** [comment]
Thank you. I see now that I can remove the policy target altogether instead to target all possible requests.
